{ lib, ... }: {
  flake.modules.homeManager.zotero =
    { config, pkgs, ... }:
    let
      inherit (lib)
        mkOption
        optionals
        optional
        types
        ;
    in
    {
      options.programs.zotero = {
        enable = mkOption {
          type = types.bool;
          default = false;
          example = true;
          description = "Whether to enable Zotero.";
        };

        package = mkOption {
          type = types.nullOr types.package;
          default = pkgs.zotero;
          defaultText = lib.literalExpression "pkgs.zotero";
          example = lib.literalExpression "pkgs.zotero.override { ... }";
          description = "Zotero package to use. Set to null to skip installation.";
        };

        addons = mkOption {
          type = types.listOf types.package;
          default = [ ];
          example = lib.literalExpression "with pkgs.zotero-addons; [ zotero-cita zotero-better-notes ]";
          description = "List of Zotero addon packages. Each must expose passthru.extensionId.";
        };

        profileName = mkOption {
          type = types.str;
          default = "default";
          description = "Zotero profile directory name.";
        };

        settings = mkOption {
          type = types.attrsOf types.raw;
          default = { };
          example = {
            "extensions.zotero.backup.max" = 10;
            "extensions.zotero.recognitionEnabled" = true;
          };
          description = "Zotero preferences written to prefs.js.";
        };
      };

      config =
        let
          pz = config.programs.zotero;

          profileDir =
            if pkgs.stdenv.hostPlatform.isDarwin then
              "Library/Application Support/Zotero/Profiles/${pz.profileName}"
            else
              ".zotero/${pz.profileName}";

          addonXpis = pkgs.buildEnv {
            name = "zotero-extensions";
            paths = map (
              pkg:
              pkgs.runCommand "${pkg.name}-xpi" { } ''
                mkdir -p $out/share/zotero/extensions
                ln -sf ${pkg}/share/zotero/addons/*.xpi $out/share/zotero/extensions/${pkg.passthru.extensionId}.xpi
              ''
            ) pz.addons;
          };

          prefsContent = ''
            // Generated by Home Manager.
            ${lib.concatStrings (
              lib.mapAttrsToList (name: value: ''
                user_pref("${name}", ${builtins.toJSON value});
              '') pz.settings
            )}
          '';
        in
        {
          assertions = optionals pz.enable (
            builtins.concatMap (pkg: [
              {
                assertion = pkg ? passthru.extensionId;
                message = ''
                  Zotero addon '${pkg.name}' does not expose a passthru.extensionId.
                  Each addon must have an extensionId for profile installation.
                '';
              }
            ]) pz.addons
          );

          home.packages = optional (pz.enable && pz.package != null) pz.package;

          home.file = lib.mkMerge (
            (optionals (pz.enable && pz.addons != [ ]) [
              {
                "${profileDir}/extensions" = {
                  source = "${addonXpis}/share/zotero/extensions";
                  recursive = true;
                };
              }
            ])
            ++ (optionals (pz.enable && pz.settings != { }) [
              {
                "${profileDir}/prefs.js" = {
                  text = prefsContent;
                };
              }
            ])
          );
        };
    };
}
