name: Eval
on:
  push:
    branches: [main]
  pull_request:
jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            extra-experimental-features = nix-command flakes pipe-operators
      - name: Evaluate flake outputs
        run: |
          nix flake check --all-systems --show-trace -L
