; stylix.conf
; description: a stylix-generated theme for Qman
; tags:        rgb, unicode, stylix
; based on:    Stylix base16 colours

[chars]
sbar_top=           ┳
sbar_vline=         ┃
sbar_bottom=        ┻
sbar_block=         █
trans_mode_name=    ┇
trans_name_loc=     ┇
box_hline=          ─
box_vline=          │
box_tl=             ╭
box_tr=             ╮
box_bl=             ╰
box_br=             ╯
arrow_up=           ⇡
arrow_down=         ⇣
arrow_lr=           ⇄

[colours]
;                   fg        bg        bold
text=               @base05@   @base00@   false
search=             @base00@   @base0A@   false
mark=               @base05@   @base03@   true
link_man=           @base0D@   @base01@   true
link_man_f=         @base0D@   @base02@   true
link_http=          @base0C@   @base01@   false
link_http_f=        @base0C@   @base02@   true
link_email=         @base09@   @base01@   false
link_email_f=       @base09@   @base02@   true
link_file=          @base0E@   @base01@   false
link_file_f=        @base0E@   @base02@   true
link_ls=            @base0B@   @base00@   true
link_ls_f=          @base0B@   @base02@   true
sb_line=            @base04@   @base00@   true
sb_block=           @base0D@   @base0D@   true
stat_indic_mode=    @base00@   @base0D@   true
stat_indic_name=    @base00@   @base0D@   true
stat_indic_loc=     @base00@   @base0D@   true
stat_input_prompt=  @base05@   @base00@   true
stat_input_help=    @base05@   @base00@   true
stat_input_em=      @base05@   @base00@   true
imm_border=         @base05@   @base00@   true
imm_title=          @base05@   @base00@   true
sp_input=           @base05@   @base00@   true
sp_text=            @base05@   @base00@   false
sp_text_f=          @base05@   @base00@   true
help_text=          @base05@   @base00@   false
help_text_f=        @base05@   @base00@   true
history_text=       @base05@   @base00@   false
history_text_f=     @base05@   @base00@   true
toc_text=           @base05@   @base00@   false
toc_text_f=         @base05@   @base00@   true

[layout]
lmargin=            3
rmargin=            5
